# Generated by Django 5.1.3 on 2024-12-02 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET'), ('JEE+NEET', 'JEE+NEET')], max_length=20)),
                ('batch', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('type', models.CharField(choices=[('numerical', 'Numerical'), ('option', 'Option')], max_length=20)),
                ('correct_answer_numerical_min', models.FloatField(blank=True, null=True)),
                ('correct_answer_numerical_max', models.FloatField(blank=True, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to='questions/')),
                ('option_a_file', models.FileField(blank=True, null=True, upload_to='questions/options/')),
                ('option_b_file', models.FileField(blank=True, null=True, upload_to='questions/options/')),
                ('option_c_file', models.FileField(blank=True, null=True, upload_to='questions/options/')),
                ('option_d_file', models.FileField(blank=True, null=True, upload_to='questions/options/')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('explanation_file', models.FileField(blank=True, null=True, upload_to='questions/explanations/')),
                ('marks_award', models.FloatField()),
                ('marks_deduct', models.FloatField()),
                ('tag', models.CharField(choices=[('AI generated', 'AI generated'), ('PYQ', 'PYQ'), ('Expected Question', 'Expected Question')], max_length=50)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='website.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_materials/')),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='website.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='website.course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='website.subject'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=100, unique=True)),
                ('duration', models.DurationField()),
                ('question_list', models.ManyToManyField(related_name='tests', to='website.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('school_name', models.CharField(max_length=255)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('student', 'Student'), ('administrator', 'Administrator')], max_length=20)),
                ('roll_no', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_response', models.JSONField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.test')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_submitted', to='website.userdata')),
            ],
        ),
    ]
