# Generated by Django 5.1.3 on 2024-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_question_chapter_question_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='chapter',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='chapter',
            field=models.ManyToManyField(related_name='study_materials', to='website.chapter'),
        ),
    ]
