# Generated by Django 5.1.3 on 2024-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_studymaterial_chapter_studymaterial_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='batch',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
