# Generated by Django 5.1.3 on 2024-12-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_test_accepting_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
