# Generated by Django 5.1.3 on 2024-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_test_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
