# Generated by Django 4.2.17 on 2024-12-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_test_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='website.course'),
        ),
    ]
