# Generated by Django 4.2.17 on 2024-12-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_userdata_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ManyToManyField(related_name='subjects', to='website.course'),
        ),
    ]
