# Generated by Django 4.2.17 on 2024-12-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_subject_course_subject_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='website.subject'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='website.course'),
        ),
    ]
