# Generated by Django 4.2.17 on 2024-12-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_chapter_subject_remove_subject_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmitted',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testsubmitted',
            name='score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='testsubmitted',
            name='json_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
